# Generated by Django 3.1.2 on 2020-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201024_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='d_profile.png', null=True, upload_to=''),
        ),
    ]
