# Generated by Django 3.1.2 on 2020-10-23 11:50

from django.db import migrations, models
import note.note_enums


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201023_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='enums',
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[(note.note_enums.NoteStatusChoice['published'], 'published'), (note.note_enums.NoteStatusChoice['draft'], 'draft'), (note.note_enums.NoteStatusChoice['deleted'], 'deleted')], max_length=255),
        ),
    ]
