# Generated by Django 3.1.2 on 2020-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20201023_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft'), ('deleted', 'deleted')], max_length=255),
        ),
    ]
